In [5]:
import math
import sys
import numpy as np

data = [[0,0],[0,1],[1,0],[1,1],[0,0],[0,1],[1,0],[1,1]] 
#outputs = []
#for i in inputs:
 #   if i > 0
  #      output.append(i)
   # elif i<=0:
     #   output.append(0)
# two input neurons
#load 4 into input
E = math.e
X = [[0,0],[0,1],[1,0],[1,1]]
weights_layer_1 = [[0.2,0.4],[0.1,0.5],[.8,1],[.3,1]]
weights_layer_2 = [[0.5,0.6],[0.2,0.7],[.1,.9]]
#weights_layer_1: two input neurons, each one leads to 4 layer_1 neurons.
#for i in data:
# three classes: or, and, and xor.        
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs,n_neurons)
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) # + self.biases
    def sigmoid(z):
         return 1/(1 + np.exp(-z))
    def reLU(z):
        return np.maximum(0,z)
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
class Activation_softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values = np.sum(exp_values, axis=1,keepdims=True)
        self.output = probabilities
class Loss:
    def calculate(self, output, y):
        sample_losses=self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss
class Loss_CCE(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-10, 1-1e-10)
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)
        negative_log_likelihoods = np.log(correct_confidences)
        

layer1 = Layer_Dense(2,4) #layer after input
layer2 = Layer_Dense(4,3) #

layer1.forward(X)
activation1 = Activation_ReLU()
activation1.forward(layer1.output)

layer2.forward(layer1.output)
activation2 = Activation_softmax()
activation1.forward(layer1.output)
activation2.forward(layer2.output)
print(activation2.output)

loss_functiion = Loss_CCE()
loss = loss_function.calculate(activation2.output, correct_vals) #correct_vals is the answer key


   # raw_prediction_L_1 =np.dot(np.array(weights_layer_1).T,X)
   # raw_prediction_L_2 =np.dot(np.array(weights_layer_2).T,raw_prediction_L_1)
   # activation_prediction=np.sigmoid(raw_prediction)
    #thats conversion to layer 1
     #error = (yactual-activation_prediction)^2

[[ 0.          0.          0.        ]
 [ 0.02489757 -0.00625885  0.01375265]
 [ 0.037596   -0.00767395 -0.05597878]
 [ 0.06249357 -0.0139328  -0.04222613]]
